
### Variables

@apiUrl = http://localhost:3010/api/v1

@menuId = 693101f85e50a4bc7d72e1d6

@eventId = 693364588d001eae8c9e5113

### All Menu Items
GET {{apiUrl}}/menu

### Menu Item by Id
GET {{apiUrl}}/menu/{{menuId}}

### All Events 
GET {{apiUrl}}/events

### Event by Id
GET {{apiUrl}}/events/{{eventId}}

### Add new MenuItem
POST {{apiUrl}}/menu/add
Content-Type: application/json

{
    "name": "test", 
    "image": "", 
    "details": "about this menu",
    "price": 3
}

### Add new Event
POST {{apiUrl}}/events/add
Content-Type: application/json

{
    "name": "test", 
    "location": "some other park", 
    "date": "2026-08-04T10:00:00",
    "time": "10:00",
    "details": "About this event",
    "image": "https://placehold.co/400x200/003366/ffc400?text=Event"
}
