
### Variables

@apiUrl = http://localhost:5000/api/v1

@menuId = 693101f85e50a4bc7d72e1d6

@eventId = 69319b1b5e50a4bc7d73a33b

### All Menu Items
GET {{apiUrl}}/menu

### Menu Item by Id
GET {{apiUrl}}/menu/{{menuId}}

### All Events 
GET {{apiUrl}}/events

### Event by Id
GET {{apiUrl}}/events/{{eventId}}

### Add new MenuItem
POST {{apiUrl}}/menu/add
Content-Type: application/json

{
    "name": "test", 
    "image": "", 
    "details": "about this menu",
    "price": 3
}

### Add new Event
POST {{apiUrl}}/events/add
Content-Type: application/json

{
    "name": "test", 
    "location": "some other park", 
    "date": "1/1/2025",
    "time": "12:00"
}
